# Generated by Django 5.2.8 on 2025-12-02 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClothProduct',
            new_name='Cloth',
        ),
        migrations.RenameModel(
            old_name='JewelleryProduct',
            new_name='Jewellery',
        ),
    ]
