# Generated by Django 5.2.8 on 2025-12-02 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_clothproduct_cloth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.URLField()),
                ('category', models.CharField(choices=[('cloth', 'Cloth'), ('jewellery', 'Jewellery')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='cloth',
            name='image',
        ),
        migrations.RemoveField(
            model_name='cloth',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cloth',
            name='price',
        ),
        migrations.RemoveField(
            model_name='jewellery',
            name='image',
        ),
        migrations.RemoveField(
            model_name='jewellery',
            name='name',
        ),
        migrations.RemoveField(
            model_name='jewellery',
            name='price',
        ),
        migrations.AddField(
            model_name='cloth',
            name='colors',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='cloth',
            name='sizes',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='jewellery',
            name='material',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cloth',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='jewellery',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
