# Generated by Django 5.2.8 on 2025-12-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_cloth_colors_cloth_collar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='package',
            field=models.TextField(blank=True, null=True),
        ),
    ]
