# Generated by Django 5.2.8 on 2025-12-04 10:35

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_cloth_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloth',
            name='country_of_origin',
        ),
        migrations.AddField(
            model_name='cloth',
            name='made_in',
            field=models.CharField(blank=True, default='India', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jewellery',
            name='colour',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jewellery',
            name='made_in',
            field=models.CharField(blank=True, default='India', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jewellery',
            name='package',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jewellery',
            name='sizes',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('FREE_SIZE', 'FREE_SIZE')], max_length=22, null=True),
        ),
        migrations.AddField(
            model_name='jewellery',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='sizes',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('FREE_SIZE', 'FREE_SIZE')], max_length=22, null=True),
        ),
    ]
