# Generated by Django 5.2.8 on 2025-12-04 11:05

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_cloth_country_of_origin_cloth_made_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='sizes',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('FREE', 'FREE')], max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='jewellery',
            name='sizes',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('FREE', 'FREE')], max_length=17, null=True),
        ),
    ]
