# Generated by Django 5.2.8 on 2025-12-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('age_category', models.CharField(choices=[('kids_boy', 'Kids - Boy'), ('kids_girl', 'Kids - Girl'), ('kids_unisex', 'Kids - Unisex'), ('adults_men', 'Adults - Men'), ('adults_women', 'Adults - Women'), ('adults_unisex', 'Adults - Unisex'), ('all_age_men', 'All Age - Men'), ('all_age_women', 'All Age - Women'), ('all_age_unisex', 'All Age - Unisex')], max_length=20)),
                ('product_category', models.CharField(choices=[('cloth', 'Cloth'), ('jewellery', 'Jewellery')], max_length=20)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_qty', models.PositiveIntegerField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('material_type', models.CharField(blank=True, max_length=100)),
                ('fit_type', models.CharField(blank=True, max_length=100)),
                ('pattern_design', models.CharField(blank=True, max_length=100)),
                ('available_sizes', models.JSONField(default=list, help_text='Available sizes (choose from): Small, Medium, Large, Free Size, 0-1, 1-2, 2-3, 3-4, 4-5, 5-6, 6-7, 7-8, 8-9, 9-10, 10-11, 11-12, 12-13, 13-14, 14-15')),
                ('age_limits', models.TextField(help_text='Example: Suitable for kids aged 4 to 7 years')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
