# Generated by Django 5.2.8 on 2025-12-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='age_limits',
            field=models.TextField(blank=True, help_text='Example: Suitable for kids aged 4 to 7 years', null=True),
        ),
    ]
