# Generated by Django 5.2.6 on 2025-12-19 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_product_shipping_charge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='shipping_charge',
            new_name='delivery_charge',
        ),
    ]
