# Generated by Django 5.2.6 on 2025-12-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_alter_product_delivery_charge_alter_product_mrp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_sizes',
            field=models.JSONField(default=list),
        ),
    ]
