# Generated by Django 5.2.8 on 2026-01-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0006_alter_product_available_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
