# Generated by Django 5.2.8 on 2026-01-07 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0007_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
