# Generated by Django 5.2.8 on 2026-01-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0008_remove_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
