# Generated by Django 5.2.8 on 2025-12-02 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_jewelleryproduct_rename_product_clothproduct_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClothProduct',
        ),
        migrations.DeleteModel(
            name='JewelleryProduct',
        ),
    ]
