# Generated by Django 5.2.8 on 2025-12-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_channel',
            field=models.CharField(choices=[('upi', 'UPI'), ('card', 'Card'), ('netbanking', 'NetBanking'), ('wallet', 'Wallet'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('prepaid', 'Prepaid'), ('cod', 'Cash on Delivery')], default='prepaid', max_length=20),
        ),
    ]
