# Generated by Django 5.2.8 on 2025-12-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_cart_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cloth',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='jewellery',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='cloth',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='jewellery',
        ),
        migrations.AddField(
            model_name='cart',
            name='product_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='product_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
