# Generated by Django 5.2.8 on 2025-12-02 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_cart_cloth_remove_cart_jewellery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
