# Generated by Django 5.2.8 on 2025-12-02 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_wishlist_user_delete_cart_delete_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
