# Generated by Django 5.2.8 on 2025-12-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_order_city_alter_order_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mrp',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
