# Generated by Django 5.2.8 on 2025-12-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_order_mrp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mrp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
