# Generated by Django 5.2.6 on 2025-12-29 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_productrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrating',
            name='product_slug',
        ),
    ]
