# Generated by Django 5.2.8 on 2026-01-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_remove_productrating_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_channel',
            field=models.CharField(blank=True, choices=[('upi', 'UPI'), ('card', 'Card'), ('netbanking', 'NetBanking'), ('wallet', 'Wallet')], max_length=20),
        ),
    ]
